POST https://localhost:8444/documents HTTP/1.1
Content-Type: application/xml

<Document></Document>

###
GET https://localhost:8444/documents HTTP/1.1


###
GET https://localhost:8444/documents/2 HTTP/1.1
